### ISSUE TITLE
set-output is deprecated, needs to be changed

### ISSUE THREAD

**Issue by darmbrust** [jenkins-x-plugins/jx-release-version#110]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

https://github.com/jenkins-x-plugins/jx-release-version/blob/a4539cf44b6d206c7ce3fb2340e240f2760dfcfe/hack/github-actions-entrypoint.sh#LL4C7-L4C7

**Comment by vbehar** [comment]
thanks for reporting this issue! it should be fixed now in the latest release

**Comment by DANIEL-ARMBRUST-VA** [comment]
wow, that was fast!
Thanks
