### ISSUE TITLE
Release `2.7.7` failed tu publish: no binaries available

### ISSUE THREAD

**Issue by dduportal** [jenkins-x-plugins/jx-release-version#123]
Hello folks,

It looks like the release build failed:

<img width="1271" alt="Capture d’écran 2024-11-20 à 07 52 35" src="https://github.com/user-attachments/assets/09cbb132-64e5-4f90-b117-6d2f1191b5d2">

The GitHub release is published but has no associated binaries:

<img width="1777" alt="Capture d’écran 2024-11-20 à 07 51 56" src="https://github.com/user-attachments/assets/e5f8bc03-1a9f-48e7-ac9d-20c3f3b56542">

**Comment by vbehar** [comment]
oops, good catch, thanks.
@msvticket would you be able to see the logs, to see what is the issue? thanks!

**Comment by msvticket** [comment]
⨯ release failed after 0s                          error=only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration 

Go releaser has been upgraded, so the configuration file needs to be updated accordingly: https://goreleaser.com/blog/goreleaser-v2/#upgrading

**Comment by vbehar** [comment]
thanks @msvticket! I'll fix it
