### ISSUE TITLE
Support for Gradle

### ISSUE THREAD

**Issue by DJViking** [jenkins-x-plugins/jx-release-version#26]
Support Gradle with reading the version from either build.gradle or gradle.properties.

It is a simple property and should be easy to get, but it can be stored in either build.gradle or gradle.properties

    version = 1.0

This tool worked on a gradle project, but only on master branch. For any release branch it output 0.0.1 if I used --same-release, and without --same-release I got an error:
failed to get new version strconv.ParseInt: parsing "51.2": invalid syntax

**Comment by alexmreis** [comment]
+1, building a project with Gradle 5 and the buildpack runs Gradle 4.6 instead of using the gradle wrapper and the version indicated therein. Should use `./gradlew`

**Comment by DJViking** [comment]
We have a PR now from @zachwhaley with Gradle Support.

Though the PR does not support Gradle version being stored in gradle.properties instead of the build.gradle file. Not sure how many who do store the version in the gradle.properties. I do it in some of my projects.

**Comment by DJViking** [comment]
Can anyone finally see to merge the PR #48?

**Comment by zachwhaley** [comment]
FYI, this is supported in our fork https://github.com/trendmicro/new-release-version ✨
