### ISSUE TITLE
Expects github credentials even after setting github token

### ISSUE THREAD

**Issue by gitops-unbxd** [jenkins-x-plugins/jx-release-version#49]
Hi ,

I'm using jx-release-version binary to create tag in github but even after setting GITHUB_AUTH_TOKEN environment it asks for credentials. 

`./jx-release-version -debug`

available environment:
OLDPWD=/home/ubuntu/jenkins-runner 
SSH_TTY=/dev/pts/0
USER=ubuntu
MAIL=/var/mail/ubuntu
PATH=/home/ubuntu/bin:/home/ubuntu/.local/bin:JAVA_HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/bin:/usr/lib/jvm/jdk-12.0.2/bin:/home/ubuntu/bin:/usr/lib/jvm/jdk-12.0.2/bin
GITHUB_AUTH_TOKEN=XXXXXXXXXXXXX
PWD=/home/ubuntu/jenkins-runner/example-flask
JAVA_HOME=/usr/lib/jvm/jdk-12.0.2
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/ubuntu
LOGNAME=ubuntu
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
LC_CTYPE=UTF-8
_=./jx-release-version
Username for 'https://github.com':

**Comment by vbehar** [comment]
I'm closing this one because in v2 we don't use the github API anymore
