### ISSUE TITLE
Version info blank on Windows

### ISSUE THREAD

**Issue by andham** [jenkins-x-plugins/jx-release-version#51]
Executing jx-release-version.exe -version on Windows 10 prints blank version info:
```
Version:
Git Tag:
Build Date:

```
This is with v1.0.42.

**Comment by vbehar** [comment]
is it better now with v2? I don't have a windows system to test, but on mac it works

**Comment by vbehar** [comment]
ok tested, I confirm that v1.0.42 did not have the version information, but v2 has the version information
