### ISSUE TITLE
Support 1 or 2 digit version syntax

### ISSUE THREAD

**Issue by andham** [jenkins-x-plugins/jx-release-version#52]
It would be great with support for other version syntax than major.minor.patch. For example major.increment or just increment.

**Comment by vbehar** [comment]
Hi, I don't really understand. Do you have some example of what you'd like to do?

**Comment by andham** [comment]
We'd like to be able to have version schemes with just 1 digit or 2 digits, not only 3. For example:
* 1, 2, 3, 4, 5, etc
* 1.0, 1.1, 1.2, 2.0, 2.1, 2.2, etc

Our use case is a continuous delivery model where the version itself doesn't really matter other than a greater version is later. There is not real need of having major.minor.bugfix or similar.

In any case, we've implemented our own logic for this as a shared library (for Jenkins, not X).
