### ISSUE TITLE
Support Gradle version from gradle.properties

### ISSUE THREAD

**Issue by DJViking** [jenkins-x-plugins/jx-release-version#83]
We have moved many of the variables in `build.gradle` over to `gradle.properties`, this includes the version.
This tool should support checking for version in `gradle.properties`, if there is no version in `build.gradle`.

**Comment by vbehar** [comment]
Good point, right now the logic is to use the first file that exists and only try to read the version from it. I'll change it to fallback on the next file if it can't find the version there.

**Comment by vbehar** [comment]
ok it will be in version 2.4.8
